app/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('particular', views.particular, name = "particular"),
    path('each/<str:title>/', views.eachdetail, name = "each"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app.urls','app'), namespace = 'app')),
    path('userlogin/', include(('userlogin.urls','userlogin'), namespace='userlogin')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userlogin/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('ulogin', views.ulogin, name ='ulogin'),
    path('ulogout', views.ulogout, name ='ulogout'),
    path('register/', views.register, name ='register'),
    path('authorize/', views.authorize, name ='authorize'),
    path('connect', views.connect, name="connect"),
]

app/models.py
import uuid
from django.db import models

class resume(models.Model):
    name = models.CharField(max_length= 200, default='', unique=True)
    contact = models.IntegerField()
    email = models.EmailField()
    address = models.CharField(max_length=200, default='' , unique=True)
    about_me = models.CharField(max_length=200, default='')
    career_objective = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.name


class course(models.Model):
    courseid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    course_name = models.CharField(max_length=200, default='' , null = False)
    course_detail = models.CharField(max_length=200, default='' , null = False)
    cover_image = models.ImageField(null = False, blank= False)

    def __str__(self):
        return self.course_name

userlogin/models.py
from django.db import models
# Create your models here.

class authorization(models.Model):
    name = models.CharField(max_length=200, default='' , unique=True)
    position = models.CharField(max_length= 50, default='', null = False)
    company_name = models.CharField(max_length=50, default='', null = False)
    email = models.EmailField()

    def __str__(self):
        return self.name

userlogin/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import authorization

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
        self.fields['username'].help_text = None

class AuthorizationForm(forms.ModelForm):
    class Meta:
        model = authorization
        fields = ["name", "position", "company_name" ,"email"]
        widgets = {
            'name' : forms.TextInput(attrs={'class' : 'form-control'}),
            'position' : forms.TextInput(attrs={'class' : 'form-control'}),
            'company_name' : forms.TextInput(attrs={'class' : 'form-control'}),
            'email' : forms.EmailInput(attrs={'class' : 'form-control'}),
        }

        def __init__(self, *args, **kwargs):
            super(AuthorizationForm, self).__init__(*args, **kwargs)
            self.fields['name'].widget.attrs['class'] = 'form-control'
            self.fields['position'].widget.attrs['class'] = 'form-control'
            self.fields['company_name'].widget.attrs['class'] = 'form-control'
            self.fields['email'].widget.attrs['class'] = 'form-control'

            self.fields['name'].help_text = None
            self.fields['position'].help_text = None
            self.fields['company_name'].help_text = None
            self.fields['email'].help_text = None

app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import course
from .decorators import unauthenticated_user_courses
# Create your views here.


def index(request):
    data = course.objects.all()
    context = {
        "data" : data,
    }
    return render(request, "index.html", context)

def particular(request):
    return render(request, "particularCourse.html")

@unauthenticated_user_courses
def eachdetail(request, title):
    each = course.objects.get(course_name = title)
    context = {
        "each" : each,
    }
    return render(request, "particularCourse.html" , context)

userlogin/views.py
from django.shortcuts import render,redirect
from .forms import CreateUserForm, AuthorizationForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from .decorators import unauthenticated_user_connect
from .models import authorization
from django.shortcuts import (get_object_or_404,
                              render,
                              HttpResponseRedirect)
from django.contrib.auth.decorators import login_required


# Create your views here.

def register(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Account Created Successfully")
            return redirect('userlogin:authorize')

    context = {
        "form" : form
    }
    return render(request, "userlogin/register.html", context)


def ulogin(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username = username, password = password)
        if user is not None:
            login(request,user)
            return redirect('app:index')
        else:
            messages.info(request, 'Username or password is incorrect!')
            return render(request, "userlogin/login.html")

    return render(request, "userlogin/login.html")


def ulogout(request):
    logout(request)
    return redirect('app:index')

def authorize(request):
    frm = AuthorizationForm()
    if request.method == "POST":
        frm = AuthorizationForm(request.POST)
        if frm.is_valid():
            frm.save()
            return redirect('userlogin:ulogin')
    context = {
        "frm": frm,
    }
    return render(request, "userlogin/authorize.html", context)

@unauthenticated_user_connect
def connect(request):
    dic = authorization.objects.all()
    context = {
        "dic" : dic,
    }
    return render(request, 'userlogin/connect.html', context)
@login_required(login_url='userlogin/ulogin')
def portfolio(request):
    return render(request, 'userlogin/portfolio.html')

@login_required(login_url='userlogin/ulogin')
def updateport(request, pk):
    port =  authorization.objects.get(id = pk)
    form = AuthorizationForm(instance=port)
    if request.method == "POST":
        form = AuthorizationForm(request.POST, request.FILES, instance=port)
        if form.is_valid():
            form.save()
            return redirect('app:index')

    context = {
        "form" : form,
    }
    return render(request, "userlogin/update.html", context)

app/templates/index.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">

  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
        <h1>Link and Learn</h1>
        <h2>We, the team of LNL aims to provide all the resources from networking and learning all at one place...</h2>
        {% if request.user.is_authenticated == False %}
        <div class="d-flex justify-content-center justify-content-lg-start">
          <a href="{% url 'userlogin:register' %}" class="btn-get-started scrollto">Get Started</a>
        </div>
        {% endif %}
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img src="{% static 'app/img/hero-img.png' %}" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>
  
</section><!-- End Hero -->

<main id="main">
  
  <!-- ======= Courses Section ======= -->
  <section id="courses" class="services section-bg">
    <div class="container" data-aos="fade-up">
      
      <div class="section-title">
        <h2>Courses</h2>
        <p>Learn at the comfort of your own home. <br> We at LNL understand how to get the most out of a course, so we are providing access to individuals to learn at their own pace.</p>
      </div>

      <div class="row">

        {% for i in data %}
        <div class="col-xl-3 mb-3 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
          <div class="icon-box d-flex flex-column align-items-center">
            <div class="icon"><i class="bx bxl-dribbble"></i></div>
            <h4><a href="{% url 'app:each' i.course_name %}">{{i.course_name}}</a></h4>
            <!-- <p>{{i.course_detail}}</p> -->
          </div>
        </div>
        {% endfor %}
        
        <div class="premiumCourses">
        <p class="text-center " style="font-size: 1.2rem">Explore some <strong>PREMIUM COURSES!</strong>
        </p>
        <div class="row">
          <div class="premiumCourse col-xl-3 mb-3 col-md-6 d-flex align-items-stretch mt-4 mt-xl-0" data-aos="zoom-in" data-aos-delay="400">
            <div class="icon-box d-flex flex-column align-items-center">
              <div class="icon"><i class="bx bx-layer"></i></div>
              <h4 class="main-heading"><a href="">Nemo Enim</a></h4>
              <h4 class="d-none fake-heading">Coming Soon</h4>
              <!-- <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p> -->
            </div>
          </div>
          <div class="premiumCourse col-xl-3 mb-3 col-md-6 d-flex align-items-stretch mt-4 mt-xl-0" data-aos="zoom-in" data-aos-delay="400">
            <div class="icon-box d-flex flex-column align-items-center">
              <div class="icon"><i class="bx bx-layer"></i></div>
              <h4 class="main-heading"><a href="">Nemo Enim</a></h4>
              <h4 class="d-none fake-heading">Coming Soon</h4>
              <!-- <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p> -->
            </div>
          </div>
          
          <div class="premiumCourse col-xl-3 mb-3 col-md-6 d-flex align-items-stretch mt-4 mt-xl-0" data-aos="zoom-in" data-aos-delay="400">
            <div class="icon-box d-flex flex-column align-items-center">
              <div class="icon"><i class="bx bx-layer"></i></div>
              <h4 class="main-heading"><a href="">Nemo Enim</a></h4>
              <h4 class="d-none fake-heading">Coming Soon</h4>
              <!-- <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p> -->
            </div>
          </div>
        </div>
      </div>
      
    </div>
    
    
  </div>
</section>
    <!-- End Services Section -->
    
    <!-- ======= Cta Section ======= -->
    <section id="cta" class="cta">
      <div class="container" data-aos="zoom-in">
        
        <div class="row">
          <div class="col-lg-9 text-center text-lg-start">
            <h3>Think & Achieve</h3>
            <p> If you think of something, you have to work on that thing to make it a truth of your life, otherwise you will be working for building some other person's dream.</p>
          </div>
        </div>
        
      </div>
    </section><!-- End Cta Section -->
    
    <!-- ======= Team Section ======= -->
    <section id="team" class="team section-bg">
      <div class="container" data-aos="fade-up">
        
        <div class="section-title">
          <h2>Team</h2>
          <p>We, the team of LNL aims to provide all the resources from networking and learning all at one place which makes very easy for the beginners as well as intermediaries to learn from their seniors.</p>
        </div>
        
        <div class="row">
          
          <div class="col-lg-6">
            <div class="member d-flex align-items-start" data-aos="zoom-in" data-aos-delay="100">
              <div class="pic"><img src="{% static 'app/img/team/team-1.jpg' %}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>Tanmay Mathur</h4>
                <span>Full Stack Developer</span>
<!--                <p>Explicabo voluptatem mollitia et repellat qui dolorum quasi</p>-->
                <div class="social">
                  <a href="" target="_blank"><i class="ri-twitter-fill"></i></a>
                  <a href="" target="_blank"><i class="ri-facebook-fill"></i></a>
                  <a href="" target="_blank"><i class="ri-instagram-fill"></i></a>
                  <a href="" target="_blank"> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div>


          <div class="col-lg-6 mt-4 mt-lg-0">
            <div class="member d-flex align-items-start" data-aos="zoom-in" data-aos-delay="100">
              <div class="pic"><img src="{% static 'app/img/team/team-1.jpg' %}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>Priyanshu Verma</h4>
                <span>Backend Developer</span>
<!--                <p>Explicabo voluptatem mollitia et repellat qui dolorum quasi</p>-->
                <div class="social">
                  <a href="" target="_blank"><i class="ri-twitter-fill"></i></a>
                  <a href="" target="_blank"><i class="ri-facebook-fill"></i></a>
                  <a href="" target="_blank"><i class="ri-instagram-fill"></i></a>
                  <a href="" target="_blank"> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-6 mt-4">
            <div class="member d-flex align-items-start" data-aos="zoom-in" data-aos-delay="100">
              <div class="pic"><img src="{% static 'app/img/team/team-1.jpg' %}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>Ayush Singh</h4>
                <span>Front-end developer</span>
<!--                <p>Explicabo voluptatem mollitia et repellat qui dolorum quasi</p>-->
                <div class="social">
                  <a href="" target="_blank"><i class="ri-twitter-fill"></i></a>
                  <a href="" target="_blank"><i class="ri-facebook-fill"></i></a>
                  <a href="" target="_blank"><i class="ri-instagram-fill"></i></a>
                  <a href="" target="_blank"> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-6 mt-4">
            <div class="member d-flex align-items-start" data-aos="zoom-in" data-aos-delay="100">
              <div class="pic"><img src="{% static 'app/img/team/team-1.jpg' %}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>Chirag Gupta</h4>
                <span>Full Stack Developer</span>
<!--                <p>Explicabo voluptatem mollitia et repellat qui dolorum quasi</p>-->
                <div class="social">
                  <a href="" target="_blank"><i class="ri-twitter-fill"></i></a>
                  <a href="" target="_blank"><i class="ri-facebook-fill"></i></a>
                  <a href="" target="_blank"><i class="ri-instagram-fill"></i></a>
                  <a href="" target="_blank"> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div>
          
        </div>
        
      </div>
    </section><!-- End Team Section -->
    
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">
        
        <div class="section-title">
          <h2>Contact</h2>
          <p>We can solve your query in person. Feel free to contact us.</p>
        </div>
        
        <div class="row" style="justify-content: space-evenly">

          <div class="col-lg-8 d-flex align-items-stretch">
            <div class="info d-flex row" ">
              <div class="detailInfo col-6">
                <div class="address">
                  <i class="bi bi-geo-alt"></i>
                  <h4>Location:</h4>
                  <p>SSCBS, Rohini, Delhi, India</p>
                </div>
  
                <div class="email">
                  <i class="bi bi-envelope"></i>
                  <h4>Email:</h4>
                  <p>ayushsinghkushwah8@gmail.com</p>
                </div>
                
                <div class="phone">
                  <i class="bi bi-phone"></i>
                  <h4>Call:</h4>
                  <p>+91 9509908688</p>
                </div>
              </div>
              <div class="map col-6">
                <iframe src="https://maps.google.com/maps?width=600&amp;height=400&amp;hl=en&amp;q=sscbs&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed" frameborder="0" style="border:0; width: 100%; height: 290px;" allowfullscreen></iframe>

              </div>
            </div>
            
          </div>
        </div>
        
      </div>
    </section><!-- End Contact Section -->
    
  </main><!-- End #main -->
  
  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="container footer-bottom clearfix">
      <div class="copyright">
        &copy; Copyright <strong><span>LNL</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  
{% endblock %}

app/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Link & Learn-The only platform you need to GROW</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'app/img/favicon.png' %}" rel="icon">
  <link href="{% static 'app/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'app/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'app/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'app/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'app/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'app/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'app/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'app/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'app/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'app/css/connect.css' %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-inner-pages ">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="{% url 'app:index' %}">LNL</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="app/img/logo.png" alt="" class="img-fluid"></a> -->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link " href="{% url 'app:index' %}#hero">Home</a></li>
          <li><a class="nav-link " href="{% url 'app:index' %}#courses">Courses</a></li>
          <li><a class="nav-link " href="{% url 'userlogin:connect' %}">Connect</a></li>
          <li><a class="nav-link " href="{% url 'app:index' %}#team">Team</a></li>
          <li><a class="nav-link " href="{% url 'app:index' %}#contact">Contact</a></li>
          {% if request.user.is_authenticated  %}
          <li><a class="nav-link scrollto" >Hello, {{user}}</a></li>
          {% endif %}
          <li>
            {% if request.user.is_authenticated %}
            <ul class="getstart">
              <li><a class="btn-get-started getstarted register" href="{% url 'userlogin:ulogout' %}">Logout</a></li>
            </ul>
            {% else %}
          <ul class="getstart">
              <li><a class="getstarted btn-get-started login" href="{% url 'userlogin:ulogin' %}">Login</a></li>
              <li><a class="btn-get-started getstarted register" href="{% url 'userlogin:register' %}">Register</a></li>
          </ul>
            {% endif %}
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header>
  <!-- End Header -->

  {% block body %}
  {% endblock %}

  <!-- Vendor JS Files -->
  <script src="{% static 'app/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'app/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'app/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'app/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'app/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'app/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'app/js/main.js' %}"></script>
  <script src="{% static 'app/js/course.js' %}"></script>

</body>

</html>

app/templates/particularCourse.html
{% extends "layout.html" %}
{% load static %}

{% block body %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <ol>
          <li><a target="_blank" href="{% url 'app:index' %}#courses">Courses</a></li>
          <li>LNL</li>
        </ol>
        <h2>{{ each.course_name }}</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">

      <div class="container d-flex flex-column align-items-center justify-content-center">

        <img src="{{ each.cover_image.url }}" alt="">
        <h5 class="description">{{ each.course_detail }}</h5>
      </div>
    </section>

  </main><!-- End #main -->

{% endblock %}

app/templates/profile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Sign Up | By Code Info</title>
    <link rel="stylesheet" href="css/signup.css" />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="./assets/css/signup.css"/>

  </head>
  <body>
    <div class="signup-box">
      <h1>Create Profile</h1>
      <form class="form_box">
        <label>Name</label>
        <input type="text" placeholder="" />
        <label class="profession" for="profession">your profession: </label>
        <select id="profession" name="profession">
          <option value="Student">Student</option>
          <option value="working_Professional">Professional</option>
        </select>
        <label>Company Name</label>
        <input type="text" placeholder="" name="Comapany_name"/>
        <label>Position</label>
        <input type="text" placeholder="" name="Position"/>
        <label>Enter Your Email</label>
        <input type="password" placeholder="" />
        <input class="sub_button" type="submit" value="Update" />
      </form>
    </div>
  </body>
</html>

userlogin/templates/userlogin/connect.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
    <div id="team" class="team section-bg">
      <div class="container seniors" data-aos="fade-up">
        <div class="row">

          {%for i in dic %}
          <div class="col-lg-3 mt-4 single_col col-3">
            <div class="member d-flex align-items-start" data-aos="zoom-in">
              <div class="member-info">
                <h4>{{i.name}}</h4>
                <span class="position">{{i.position}}</span>
                <p class="company">{{i.company_name}}</p>
                <div class="social">
                  <a href="mailto:{{i.email}}"><img class="img" src="{% static 'app/img/mail.png' %}" alt=""></a>
                </div>

              </div>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>
    </div>
{% endblock %}

userlogin/templates/userlogin/login.html
{% load static %}
{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Signin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">





<link href="/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
    html,
body {
  height: 100%;
}

body {
      display: flex;
      align-items: center;
      padding-top: 40px;
      padding-bottom: 40px;
      background-color: #f5f5f5;
    }

    .form-signin {
      max-width: 330px;
      padding: 15px;
    }

    .form-signin .form-floating:focus-within {
      z-index: 2;
    }

    .form-signin input[type="email"] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
    }

    .form-signin input[type="password"] {
      margin-bottom: 10px;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">

<main class="form-signin w-100 m-auto">
  <form method="post" action="">
      {% csrf_token %}
<!--    <img class="mb-4" src="/docs/5.2/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">-->
    <h3>Sign In</h3>
      <br>
    <div class="form-floating">
      <input type="text" class="form-control" id="floatingInput" placeholder="Username" name="username">
      <label for="floatingInput">Username</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
      <label for="floatingPassword">Password</label>
    </div>
      <br>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <br><br>
    <p>Don't have an account?
      <a href="{% url 'userlogin:register' %}">Register</a> </p>
  </form>
</main>



  </body>
</html>

{% endblock %}